# Generated by Django 6.0.7 on 2026-07-28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="choretask",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="choretask",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="chores_task_quantity_at_least_one",
            ),
        ),
    ]
