# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models


def split_active_task_quantities(apps, schema_editor):
    chore_task = apps.get_model("chores", "ChoreTask")
    tasks = chore_task.objects.filter(is_done=False, quantity__gt=1).iterator()
    for task in tasks:
        extra_tasks = [
            chore_task(
                session_id=task.session_id,
                title=task.title,
                quantity=1,
                assignee_id=task.assignee_id,
                source_template_id=task.source_template_id,
                is_done=False,
                created_by_id=task.created_by_id,
            )
            for _ in range(task.quantity - 1)
        ]
        chore_task.objects.bulk_create(extra_tasks)
        task.quantity = 1
        task.save(update_fields=["quantity"])


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0002_choretask_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="choretask",
            name="chores_template_once_per_session",
        ),
        migrations.AddField(
            model_name="choretask",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(split_active_task_quantities, migrations.RunPython.noop),
    ]
