# Generated by Django 6.0.7 on 2026-07-28

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantCommand",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_id", models.UUIDField()),
                ("source", models.CharField(choices=[("TEXT", "Text"), ("AUDIO", "Audio")], max_length=8)),
                ("transcript", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("RECEIVED", "Received"), ("NEEDS_CONFIRMATION", "Needs confirmation"), ("UNRESOLVED", "Unresolved"), ("EXECUTED", "Executed"), ("CANCELLED", "Cancelled"), ("FAILED", "Failed"), ("EXPIRED", "Expired")], default="RECEIVED", max_length=20)),
                ("action_type", models.CharField(choices=[("ADD_GROCERY_ITEM", "Add grocery item"), ("ADD_CHORE_TASK", "Add chore task"), ("ADD_TALK_LATER_TOPIC", "Add Talk Later topic"), ("NONE", "None")], default="NONE", max_length=24)),
                ("proposal", models.JSONField(blank=True, default=dict)),
                ("user_message", models.TextField(blank=True, default="")),
                ("result_url", models.CharField(blank=True, default="", max_length=500)),
                ("result_label", models.CharField(blank=True, default="", max_length=600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_commands", to="households.household")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_commands", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="assistantcommand",
            index=models.Index(fields=["user", "status", "-created_at"], name="ai_command_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantcommand",
            index=models.Index(fields=["expires_at"], name="ai_command_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="assistantcommand",
            constraint=models.UniqueConstraint(fields=("user", "household", "request_id"), name="ai_command_user_household_request"),
        ),
    ]
