# Generated by Django 6.0.7 on 2026-07-27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(2048)],
                    ),
                ),
                (
                    "p256dh",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(512)]
                    ),
                ),
                (
                    "auth",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(256)]
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(fields=["user", "-updated_at"], name="push_notifi_user_id_49b905_idx"),
        ),
    ]
