# Generated by Django 6.0.7 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("push_notifications", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
