# Generated by Django 6.0.7 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("push_notifications", "0003_pushsubscription_last_activity_at")]

    operations = [
        migrations.CreateModel(
            name="ReleaseAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_id", models.CharField(max_length=128, unique=True)),
                ("notes", models.TextField()),
                ("attempted_subscription_count", models.PositiveIntegerField(default=0)),
                ("successful_delivery_count", models.PositiveIntegerField(default=0)),
                ("announced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
