# Generated by Django 6.0.7 on 2026-07-28 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_processed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_discussion_topics', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_discussion_topics', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='households.household')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['household', 'is_done', '-updated_at'], name='talk_later_pending_idx'), models.Index(fields=['is_done', 'scheduled_for', 'reminder_processed_at', 'reminder_claimed_at'], name='talk_later_due_idx'), models.Index(fields=['household', 'is_done', 'scheduled_for'], name='talk_later_upcoming_idx')],
            },
        ),
    ]
