# Generated by Django 6.0.7 on 2026-07-22 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('🛒', 'Shopping cart'), ('🇹🇷', 'Turkish flag'), ('🏠', 'Home'), ('🐈', 'Cat'), ('🧴', 'Bottle'), ('📦', 'Package')], default='🛒', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_shopping_lists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shopping_lists', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='households.household')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_shopping_items', to=settings.AUTH_USER_MODEL)),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_shopping_items', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['household', 'status', '-updated_at'], name='shopping_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['household', 'status', '-completed_at'], name='shopping_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('status', 'ACTIVE')), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='shopping_list_completion_metadata'),
        ),
        migrations.AddConstraint(
            model_name='shoppingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_purchased', False), ('purchased_at__isnull', True), ('purchased_by__isnull', True)), models.Q(('is_purchased', True), ('purchased_at__isnull', False), ('purchased_by__isnull', False)), _connector='OR'), name='shopping_item_purchase_metadata'),
        ),
    ]
