# Generated by Django 6.0.7 on 2026-07-22 14:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AddField(
            model_name="shoppingitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="shopping_item_quantity_at_least_one",
            ),
        ),
    ]
