# Generated by Django 6.0.7 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0002_shoppingitem_description_shoppingitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="icon",
            field=models.CharField(
                choices=[
                    ("🛒", "Shopping cart"),
                    ("🇹🇷", "Turkish flag"),
                    ("🏠", "Home"),
                    ("🐈", "Cat"),
                    ("🧴", "Bottle"),
                    ("📦", "Package"),
                    ("albert-heijn", "Albert Heijn"),
                    ("jumbo", "Jumbo"),
                ],
                default="🛒",
                max_length=16,
            ),
        ),
    ]
